server:
  port: 8087

spring:
  application:
    name: notification-service
  profiles:
    active: dev

    spring:
      # Cấu hình Kafka để lắng nghe (Consumer)
      kafka:
        bootstrap-servers: localhost:9092
        consumer:
          group-id: notification-group
          key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
          value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
          properties:
            spring.json.trusted.packages: "*"

      # Cấu hình gửi Mail thực tế
      mail:
        host: smtp.gmail.com
        port: 587
        username: theanh199405023@gmail.com
        password: lbwcahcnaealcyzb
        properties:
          mail:
            smtp:
              auth: true
              starttls:
                enable: true
              connectiontimeout: 5000
              timeout: 5000
              writetimeout: 5000

  datasource:
    url: jdbc:postgresql://ep-red-river-amkvj9tx-pooler.c-5.us-east-1.aws.neon.tech/notification_db?sslmode=require
    username: neondb_owner
    password: npg_1lr8XJZoFbMS
    driver-class-name: org.postgresql.Driver

    mail:
      host: smtp.gmail.com
      port: 587
      username: ${MAIL_USERNAME}
      password: ${MAIL_PASSWORD}
      properties:
        mail.smtp.auth: true
        mail.smtp.starttls.enable: true

    jpa:
      hibernate:
        ddl-auto: validate
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.PostgreSQLDialect

    flyway:
      enabled: true
      baseline-on-migrate: true
      locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    root: INFO
    web: INFO

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html