server:
  port: 8081

spring:
  application:
    name: identify-service
  profiles:
    active: dev

#  datasource:
#    url: jdbc:postgresql://localhost:5434/food_db?options=-c%20timezone=UTC
#    username: root
#    password: Theanh123
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    root: INFO
    web: INFO

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html