spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  cloud:
    gateway:
      routes: # điều hướng request đến service tương ứng thông qua chỉ định trên url
        - id:   identify-service
          uri: ${IDENTITY_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/auth/**, /v3/api-docs/identify-service
          filters:
            - name: Authentication
#            - RewritePath=/tours/(?<segment>.*), /$\{segment}
#            - CustomizeFilter
        - id: core-service
          uri: ${CORE_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/core/**, /v3/api-docs/core-service
#          filters:
#            - RewritePath=/cores/(?<segment>.*), /$\{segment} # thay thế ký tự /account/ thành /
#            - CustomizeFilter
 
        - id: search-service
          uri: ${SEARCH_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/search/**, /v3/api-docs/search-service
#          filters:
#            - RewritePath=/search/(?<segment>.*), /$\{segment} # thay thế ký tự /mail/ thành /
#            - CustomizeFilter
        - id: booking-service
          uri: ${BOOKING_SERVICE_URL:http://localhost:8084}
          predicates:
            - Path=/api/v1/bookings/**, /bookings/**, /v3/api-docs/booking-service
          filters:
            - Authentication
#          filters:
#            - RewritePath=/bookings/(?<segment>.*), /$\{segment} # thay thế ký tự /product/ thành /
#            - CustomizeFilter
        - id: payment-service
          uri: ${PAYMENT_SERVICE_URL:http://localhost:8085}
          predicates:
            - Path=/payments/**, /v3/api-docs/payment-service
          filters:
            - name: Authentication
#            - RewritePath=/payments/(?<segment>.*), /$\{segment} # thay thế ký tự /order/ thành /
        - id: support-service
          uri: ${SUPPORT_SERVICE_URL:http://localhost:8086}
          predicates:
            - Path=/supports/**, /v3/api-docs/support-service
#          filters:
#            - RewritePath=/supports/(?<segment>.*), /$\{segment} # thay thế ký tự /order/ thành /
#        - id: mail-service
#          uri: http://localhost:8087
#          predicates:
#            - Path=/mail/**, /v3/api-docs/mail-service
#          filters:
#            - RewritePath=/mail/(?<segment>.*), /$\{segment} # thay thế ký tự /mail/ thành /
#            - CustomizeFilter
        - id: notification-service
          uri: ${NOTIFICATION_SERVICE_URL:http://localhost:8087}
          predicates:
            - Path=/notification/**, /v3/api-docs/notification-service
#          filters:
#            - RewritePath=/notification/(?<segment>.*), /$\{segment} # thay thế ký tự /mail/ thành /
#            - CustomizeFilter
        - id: ai-service
          uri: ${AI_SERVICE_URL:http://localhost:8000}
          predicates:
            - Path=/ai/**, /v3/api-docs/ai-service
          filters:
            - RewritePath=/ai/(?<segment>.*), /api/$\{segment}



springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - url: /v3/api-docs/identify-service
        name: Identity Service
      - url: /v3/api-docs/support-service
        name: Support Service
      - url: /v3/api-docs/core-service
        name: Core Service
      - url: /v3/api-docs/payment-service
        name: Payment Service
      - url: /v3/api-docs/search-service
        name: Search Service
      - url: /v3/api-docs/booking-service
        name: Booking Service\
      - url: /v3/api-docs/notification-service
        name: Notification Service
      - url: /v3/api-docs/ai-service
        name: AI Service

#redis:
#  host: localhost
#  port: 6379

#grpc:
#  client:
#    verify-token-service:
#      address: static://localhost:9091
#      enableKeepAlive: true
#      keepAliveWithoutCalls: true
#      negotiationType: plaintext