server:
  port: 8084


spring:
  application:
    name: booking-service

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      retries: 0

  datasource:
    url: jdbc:postgresql://ep-red-river-amkvj9tx-pooler.c-5.us-east-1.aws.neon.tech/booking_db?sslmode=require
    username: neondb_owner
    password: npg_1lr8XJZoFbMS
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

  flyway:
    enabled: false
#    baseline-on-migrate: true
#    locations: classpath:db/migration

  jackson:
    serialization:
      write-dates-as-timestamps: false
  management:
    endpoints:
      web:
        exposure:
          include: '*'

  logging:
    level:
      root: INFO
      org.springframework.web: INFO
      org.hibernate.SQL: DEBUG
      org.flywaydb: INFO

  springdoc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui.html
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # Địa chỉ của Eureka Server
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true