spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true

  datasource:
    url: jdbc:postgresql://ep-red-river-amkvj9tx-pooler.c-5.us-east-1.aws.neon.tech/payment_db?sslmode=require
    username: neondb_owner
    password: npg_1lr8XJZoFbMS

  kafka:
    bootstrap-servers: localhost:29092

sepay:
  bank-code: ICB
  account-no: 109876820087
  template: compact

stripe:
  secret-key: sk_test_REPLACE_WITH_YOUR_STRIPE_SECRET_KEY
  webhook-secret: whsec_REPLACE_WITH_YOUR_STRIPE_WEBHOOK_SECRET
  success-url: http://localhost:3000/payment/success
  cancel-url: http://localhost:3000/payment/cancel

#springdoc:
#  api-docs:
#    enabled: true
#  swagger-ui:
#    enabled: true

openapi:
  service:
    api-docs: payment-service
    server: http://localhost:${server.port}
    title: user service
    version: 1.0.0
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: update
#    show-sql: false
#    properties:
#      hibernate:
#        format_sql: true