server:
  port: 8083

spring:
  application:
    name: search-service
  profiles:
    active: dev

  kafka:
    consumer:
      group-id: search-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # DÙNG ErrorHandlingDeserializer ở đây
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        # Chỉ định delegate là JsonDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        # ÉP KIỂU mặc định về class của Search Service
        spring.json.value.default.type: com.tour.search.event.TourSearchEvent
        # QUAN TRỌNG NHẤT: Lờ đi thông tin class trong Header (com.tour.core...)
        spring.json.use.type.headers: false

  data: # Thêm nhánh này
    elasticsearch:
      repositories:
        enabled: true
  elasticsearch: # Nhánh này giữ nguyên cho uris
    uris: ${SPRING_ELASTICSEARCH_URIS:http://localhost:9200}
#    username: elastic
#    password: your_password
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    root: INFO
    web: INFO

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html