server:
  port: 8081

jwt:
  signerKey: my-super-secret-key-that-is-at-least-64-bytes-long-1234567890-abcdef
spring:
  application:
    name: identity-service


  datasource:
    url: jdbc:postgresql://ep-red-river-amkvj9tx-pooler.c-5.us-east-1.aws.neon.tech/identity_db?sslmode=require
    username: neondb_owner
    password: npg_1lr8XJZoFbMS
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

  flyway:
    enabled: false
#    baseline-on-migrate: true
#    locations: classpath:db/migration

  management:
    endpoints:
      web:
        exposure:
          include: '*'

  logging:
    level:
      root: INFO
      org.springframework.web: INFO
      org.hibernate.SQL: DEBUG
      org.flywaydb: INFO

  springdoc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui.html

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # Địa chỉ của Eureka Server
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
