ALTER TABLE tours
    ADD COLUMN IF NOT EXISTS overview TEXT,
    ADD COLUMN IF NOT EXISTS itinerary JSONB,
    ADD COLUMN IF NOT EXISTS inclusions JSONB,
    ADD COLUMN IF NOT EXISTS exclusions JSONB,
    ADD COLUMN IF NOT EXISTS policies JSONB,
    ADD COLUMN IF NOT EXISTS rating DECIMAL(3,2) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS review_count INTEGER DEFAULT 0;