server:
  port: 8086

spring:
  application:
    name: support-service
  profiles:
    active: dev

  data:
    mongodb:
      uri: mongodb+srv://theanh123:theanh123@cluster0.foryjm4.mongodb.net/tour_db?retryWrites=true&w=majority&appName=Cluster0


management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    root: INFO
    web: INFO

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # Địa chỉ của Eureka Server
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true