server:
  port: 8082

spring:
  application:
    name: core-service
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379

  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://ep-red-river-amkvj9tx-pooler.c-5.us-east-1.aws.neon.tech:5432/core_db?sslmode=require&channel_binding=require&currentSchema=public
    username: core_user
    password: X9!mQ2#vLp7$Rt28
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true

  flyway:
    enabled: false
#    baseline-on-migrate: true
#    schemas: public
#    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.flywaydb: INFO

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

jwt:
  signerKey: my-super-secret-key-that-is-at-least-64-bytes-long-1234567890-abcdef